### ISSUE TITLE
Fatal error: Call to undefined function mysql_connect()

### ISSUE THREAD

**Issue by lanjingling0510** [EvaEngine/Dockerfiles#3]

**Comment by AlloVince** [comment]
provide more info please

**Comment by lanjingling0510** [comment]
l want to use mysql_connect() in php code ,what extension do l need?

**Comment by lanjingling0510** [comment]
In my php config,I specify mysql host "127.0.0.1:3306"  .Is it right ?

**Comment by AlloVince** [comment]
if you use Mac, the mysql host should point to boot2docker vm IP

**Comment by lanjingling0510** [comment]
thinks, you are right!
